version: '3'
services:
  selenium-firefox: #TODO à lancer avant googlethon
    restart: always
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  googlethon:
    image: reachhubcorp/googlethon:latest
    container_name: googlethon
#    build:
#      context: ./context/
    ports:
      - "2223:2223"
    environment:
      KAFKA_IP: "${ipkafka}"
      KAFKA_PORT: 8092
      NUMBER_RESULT: 10
      TOPIC_IN: housToGoogle
      TOPIC_OUT_SCRAPY: urlToScrapy
      DEBUG: INFO
      SEARCH_TYPE: SearchResult
      REMOTE_FIREFOX_IP: ${ipremotefirefox}
      REMOTE_FIREFOX_PORT: ${portremotefirefox}
